config/routes.rb
Pinteresting::Application.routes.draw do
  resources :pins

  devise_for :users
  root "pins#index"
  get "about" => "pages#about" # creates about_path
  get "contact" => "pages#contact" 
  get "signup" => "pages#signup"
  get "login" => "pages#login"
  get "pins" => "pins#index"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  
  has_attached_file :image, 
                    :styles => { :medium => "300x300", :thumb => "100x100" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :image, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
  has_many :pins, dependent: :destroy

  validates :name, presence: true
  validates :name, length: { minimum: 3 }
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user_from_token!
  before_filter :authenticate_user!
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def authenticate_user_from_token!
    user_email = params[:user_email].presence
    user = user_email && User.find_by_email(user_email)

    if user && Devise.secure_compare(user.authentication_token, params[:user_token])
      sign_in user, store: false
    end
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
  
  def about
  end

  def contact
  end

  def signup
  end

  def login
  end
    
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]


  def index 
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 25)
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new' 
    end
  end
  
  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.' 
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(params[:user])
    
    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        UserMailer.welcome_email(@user).deliver
        
        format.html { redirect_to(@user, notice: 'User was successfully created.') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <!-- <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> -->
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
	<span class="sr-only">Toggle navigation</span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
      </button>
      <%= link_to "PinTrance", root_path, class: "navbar-brand" %>
    </div>
    
    <!-- Collect the nav links, forms, and other content for toggling -->
    <!-- <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"> -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">

	<% if user_signed_in? %>
	  <li>
	    <%= link_to new_pin_path do %>
	      <span class="glyphicon glyphicon-plus-sign"></span> New
	    <% end %>	  
	  </li>
	<% end %>

	<li>
	  <%= link_to root_path do %>
	    <span class="glyphicon glyphicon-home"></span> Home
	  <% end %>
	</li>

	<li>
	  <%= link_to about_path do %>
	    <span class="glyphicon glyphicon-question-sign"></span> About
	  <% end %>
	</li>

	<% if user_signed_in? %>
	  <li>
	    <%= link_to edit_user_registration_path do %> 
	      <span class="glyphicon glyphicon-cog"></span> Account
	    <% end %>
	  </li>
	<% else %>
	  <li>
	    <%= link_to new_user_registration_path do %>
	      <span class="glyphicon glyphicon-pencil"></span> Sign Up
	    <% end %>
	  </li>
	<% end %>
	<li>
	  <%= link_to contact_path do %>
	    <span class="glyphicon glyphicon-envelope"></span> Contact
	  <% end %>
	</li>
	<% if user_signed_in? %>
	  <li>
	    <%= link_to pins_path do %>
	      <span class="glyphicon glyphicon-th"></span> Pins
	    <% end %>
	  </li>
          <li>
	    <%= link_to destroy_user_session_path, method: :delete do %>
	      <span class="glyphicon glyphicon-arrow-right"></span> Log Out
	    <% end %>
	  </li>
	<% else %>
	  <li>
	    <%= link_to new_user_session_path do %>
	      <span class="glyphicon glyphicon-arrow-right"></span> Log In
	    <% end %>
	  </li>
	<% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pintrance</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/pages/_home.html.erb
<div class="tempfix">
  <div class="jumbotron center">
    <h2>Welcome to PinTrance!</h2>
    <p>
      <%= link_to "Log In", new_user_session_path, class: "btn btn-primary btn-lg" %>  
      <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
    </p>
  </div>
</div>

app/views/pages/about.html.erb
<div class="tempfix">
  <div class="jumbotron">
    <h1>About us</h1>
    <p>Wanna zone out? Start watching pins automatically changing and go into a trance!</p>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="tempfix">
  <div class="jumbotron">
    <h1>Reach Out</h1>
    <p>Please feel free to contact us: info@pintrance.com</p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
  <h1>Welcome to PinTrance!</h1>
  <br/>
  <% if user_signed_in? %>
    
    <div class="center">
      <%= image_tag Pin.last.image.url, class: "img-frame" if Pin.last.image.url != "/images/original/missing.png" %>
      <div class="shout">
	<%= Pin.last.description %>
      </div>
      <br/>
    </div>

    <%= link_to "New Pin", new_pin_path, class: "btn btn-primary btn-lg" %>      
  <% else %>
    <p>
      <%= link_to "Log In", new_user_session_path, class: "btn btn-primary btn-lg" %>  
      <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
    </p>
  <% end %>


</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, maxlength: '100', style: 'font-size: 20px; width: 75%; height: 50px;', class: 'form-control' %>
  </div> 

  <div class="field form-group"> 
    <%= f.label :image %><br> 
    <%= f.file_field :image, style: 'font-size: 20px; width: 75%; height: 50px;', class: "form-control" %> 
  </div> 


  <div class="actions form-group">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="tempfix">
  <h1>Editing pin</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @pin %> |
  <%= link_to 'Back', pins_path %>
</div>

app/views/pins/index.html.erb
<div class="tempfix">
  <%= render 'pages/home' unless user_signed_in? %>

  <div id="pins", class="transitions-enabled", style="margin-top: 7em;">

    <% @pins.each do |pin| %>
      <div class="box panel panel-default custom-box-styles">
	<%= link_to image_tag(pin.image.url(:medium)), pin %>      
	<div class="panel-body">
	  <%= pin.description %><br/>
	  <strong><%= pin.user.name if pin.user %></strong>
	  <% if current_user && (pin.user == current_user) %>
	    <div class="actions" style="float: right;">
	      <%= link_to edit_pin_path(pin) do %>
		<span class="glyphicon glyphicon-edit"></span>
	      <% end %>
	      <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
		<span class="glyphicon glyphicon-remove-circle"></span> 
	      <% end %>
	    </div>
	  <% end %>
	</div>
      </div>
    <% end %>

  </div>

  <div class="center">
    <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
  </div>

  <div class="panel-footer">

    <div class="container">
      <% if user_signed_in? %>
	<%= link_to 'New Pin', new_pin_path, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

</div>

app/views/pins/new.html.erb
<div class="tempfix">
  <h1>New pin</h1>

  <div class="container panel-body">
    <%= render 'form' %>
  </div>

  <%= link_to 'Back', pins_path %>
</div>

app/views/pins/show.html.erb
<div style="margin-top: 10em;">

  <div class="row">
    <div class="col-md-offset-2 col-md-8">
      <div class="panel panel-default">
	<div class="panel-heading center">
	  <%= image_tag @pin.image.url(:medium) %>
	</div>
	<div class="panel-body">
	  <p>
	    <strong><%= @pin.user.name %></strong>
	  </p>

	  <p>
	    <%= @pin.description %>
	  </p>

	  <% if @pin.user == current_user %>
	    <%= link_to edit_pin_path(@pin), class: "btn btn-primary" do %>
	      <span class="glyphicon glyphicon-arrow-right"></span> Edit 
	    <% end %>

	    <%= link_to @pin, class: "btn btn-primary", method: :delete, data: { confirm: 'Are you sure?' } do %>
	      <span class="glyphicon glyphicon-remove-circle"></span> Delete
	    <% end %>
	  <% end %>

	  <div style="float: right">
	    <% if user_signed_in? %>
	      <%= link_to new_pin_path, class: "btn btn-primary" do %> 
		<span class="glyphicon glyphicon-plus-sign"></span> New Pin
	      <% end %>
	    <% end %>

	    <%= link_to pins_path, class: "btn btn-primary" do %>
	      <span class="glyphicon glyphicon-th"></span> Pins 
	    <% end %>
	  </div>

	</div>
      </div>
    </div>
  </div>
</div>